name: lsst-corrector
channels:
  - astropy
  - conda-forge
  - defaults
dependencies:
  - astropy=4.3.1
  - ipython=7.31.1
  - joblib=1.1.0
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - numba=0.55.1
  - numpy=1.21.5
  - pandas=1.3.4
  - python=3.8.13
  - scipy=1.7.3
  - skyfield=1.45
  - spiceypy=5.0.1
